// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAu7h3XztQirBGbf8rEIPIAQ63drLqMgU',
    appId: '1:78397942674:web:5fe3a2597073bddc54af4b',
    messagingSenderId: '78397942674',
    projectId: 'civilapp-5265b',
    authDomain: 'civilapp-5265b.firebaseapp.com',
    storageBucket: 'civilapp-5265b.appspot.com',
    measurementId: 'G-W131KN6GC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf4R5FPPagYUjzPASZtMZrHtEdiyx-CxM',
    appId: '1:78397942674:android:8c850b12cd51490f54af4b',
    messagingSenderId: '78397942674',
    projectId: 'civilapp-5265b',
    storageBucket: 'civilapp-5265b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOj8RM80xkDncf957W20OhqPBd-QhUKs8',
    appId: '1:78397942674:ios:190c91f5ab2fcdc654af4b',
    messagingSenderId: '78397942674',
    projectId: 'civilapp-5265b',
    storageBucket: 'civilapp-5265b.appspot.com',
    androidClientId: '78397942674-p9l5i7kd06584cgsmc5g1116dmuqi6hi.apps.googleusercontent.com',
    iosClientId: '78397942674-39eukt85lln0mjgb9f931tfnuqddq7o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.civils1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOj8RM80xkDncf957W20OhqPBd-QhUKs8',
    appId: '1:78397942674:ios:af32b073541c471754af4b',
    messagingSenderId: '78397942674',
    projectId: 'civilapp-5265b',
    storageBucket: 'civilapp-5265b.appspot.com',
    androidClientId: '78397942674-p9l5i7kd06584cgsmc5g1116dmuqi6hi.apps.googleusercontent.com',
    iosClientId: '78397942674-jpdatbjpbk7r6vjuvu43m3jd29h5v01d.apps.googleusercontent.com',
    iosBundleId: 'com.example.civils1.RunnerTests',
  );
}
